version: 2
updates:
 - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "mouse-follower"
        versions: ["^1.x"]
