version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "15:12"
      timezone: "Africa/Nairobi"
    open-pull-requests-limit: 12
    # ignore:
    #   - dependency-name: "@builder.io/partytown"
    #     versions: ["^0.10.x"]
