version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "16:00"
      timezone: "Africa/Nairobi"
    open-pull-requests-limit: 14
    ignore:
      - dependency-name: "@builder.io/partytown"
        versions: ["^0.10.x"]
      - dependency-name: "@babel/preset-env"
        versions: [">= 8.0.0"]
      - dependency-name: "chart.js"
        versions: [">= 3.0.0"]
      - dependency-name: "typescript"
        versions: [">= 6.0.0"]
      - dependency-name: "uuid"
        versions: [">= 10.0.0"]
